### ISSUE TITLE
samplecode/remoteattestation fails to build on baiduxlab/sgx-rust:1804-1.0.8

### ISSUE THREAD

**Issue by piotr-roslaniec** [apache/teaclave-sgx-sdk#123]
Hello.

I've tried running `samplecode/remoteattestation/Application` on `baiduxlab/sgx-rust:1804-1.0.8` image but ecountered following issue:

```bash
$ make 
# redacted
In file included from ../MessageHandler/MessageHandler.h:41:0,
                 from isv_app/isv_app.cpp:36:
../GoogleMessages/Messages.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
../GoogleMessages/Messages.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
../GoogleMessages/Messages.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
^Cmake: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
```
In `remoteattestation/GoogleMessages/Messages.pb.h` we see the expected version of `protoc`:
```C
#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif
```
The version shipped with image is newer:
```bash
$ protoc --version
libprotoc 3.0.0
```
I've installed `protoc@2.6.0` using [this gist](https://gist.github.com/samklr/0b8a0620f82005e7f556)
```bash
#! /bin/bash
# https://gist.github.com/samklr/0b8a0620f82005e7f556
wget https://github.com/google/protobuf/releases/download/v2.6.0/protobuf-2.6.0.tar.gz
tar xzf protobuf-2.6.0.tar.gz
cd protobuf-2.6.0
sudo apt-get update
sudo apt-get install build-essential
sudo ./configure
sudo make
sudo make check
sudo make install 
sudo ldconfig
protoc --version
# prints libprotoc 2.6.0
```
You might need to start new shell session for changes to take effect.
After that `remoteattestation/Application`  compiles fine but crashes on start instead:
```bash
$ ./app
Segmentation fault (core dumped)
```
On the `baiduxlab/sgx-rust:latest` (`baiduxlab/sgx-rust:1604-1.0.7` at the time of writing) it compiles just fine.

My guess is that `baiduxlab/sgx-rust:1804-1.0.8` is not stable yet (hence `latest` points to different image) but I wanted to make this issue as a reference.

Thanks.

**Comment by dingelish** [comment]
Hi there, samplecode/remoteattestation does not support 18.04 because it's origin [linux-sgx-remoteattestation](https://github.com/svartkanin/linux-sgx-remoteattestation) does not support 18.04.

Old fashioned remote attestation only provides SIGMA protocol and key derivation -- lack of transportation layer security. One needs to implement another layer of encryption/decryption to use it. So it's not a recommended way to proceed RA in the old style.

I would recommend you to move forward to the newer style of ra which is embedded in TLS. The algorithm comes from Intel's [sgx-ra-tls](https://github.com/cloud-security-research/sgx-ra-tls) and the corresponding implementation is in samplecode/mutual-ra and samplecode/ue-ra. We implement sgx-ra-tls with Rustls, a memory-safe TLS termination to provide memory safety guarantees and you'd not worry about heart bleed anymore.

**Comment by dingelish** [comment]
You correctly find the problem and we used to provide a solution one year ago
https://github.com/baidu/rust-sgx-sdk/blob/279e7f9a044654d2e3aebdba59f85b696e73fd25/dockerfile/experimental/Dockerfile

The experimental dockerfile includes setup of protobuf 3.4.1. And this 3.4.1 is installed before any other libraries so that it could replace the system's protobuf and make remote attestation work. Later after we implemented sgx-ra-tls, we think that there is no need to maintain this old-fashioned code sample in a newer system, with additional special setup of protobuf. I think this is not a bug of this SDK should resolve. If you really want to use it, please refer to the above Dockerfile and use protobuf 3.4.1 on this example -- everything should be fine.

**Comment by piotr-roslaniec** [comment]
@dingelish 
Thank you for this extensive explanation. I was not aware of the differences between the old and the new style of RA. I will look at other `samplecode/` examples you've mentioned.
