### ISSUE TITLE
cannot transmute between types of different sizes, or dependently-sized types

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#185]
I'm trying to build the `sgx-types` dependency for [my project](https://github.com/encointer/encointer-app/commit/d55f748d915fc701a023eab86fcf2cc777d0b07b). I get the following error:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
    --> /home/abrenzikofer/.cargo/git/checkouts/rust-sgx-sdk-fc8771c5c45bde9a/4508450/sgx_types/src/macros.rs:115:24
     |
115  |                   unsafe{macros::transmute([0u8; $size])}
     |                          ^^^^^^^^^^^^^^^^^
     | 
    ::: /home/abrenzikofer/.cargo/git/checkouts/rust-sgx-sdk-fc8771c5c45bde9a/4508450/sgx_types/src/types.rs:1413:1
     |
1413 | / impl_struct_default! {
1414 | |     sgx_ql_qv_supplemental_t, 120;
1415 | | }
     | |_- in this macro invocation
     |
     = note: source type: `[u8; 120]` (960 bits)
     = note: target type: `types::sgx_ql_qv_supplemental_t` (928 bits)


```

I'm building with 

```
export CC=i686-linux-android16-clang
cargo +nightly-2019-10-04-x86_64-unknown-linux-gnu build --target i686-linux-android --release
```

The same thing worked with v1.0.9 but it fails with v1.1.0
Also, it works with other targets (armv7-linux-androideabi and aarch64-linux-android)

**Comment by dingelish** [comment]
Is this [rust isssue #61956](https://github.com/rust-lang/rust/issues/61956#issuecomment-503626904)?

**Comment by brenzi** [comment]
don't know. anyway, I found a workaround. The sgx-types dependency can be avoided for my android crate, so that's what I did.
